name: Daily Commit Bot

on:
  schedule:
    # Runs every day at 02:30 AM UTC (Adjust as needed)
    - cron: "30 2 * * *"

  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "22f3001316@ds.study.iitm.ac.in"

      - name: Make a commit
        run: |
          date > last_run.txt  # Save current date to a file
          git add last_run.txt
          git commit -m "Automated commit: $(date)"
          git push
